### PR TITLE
Add explainer links to AR and Gamepad Modules

### PR DESCRIPTION
**Pull request by Yonet**

### CODE REVIEW

**Review by himorin — APPROVED** [review]
+1, but I bit wondered whether it is a good way that we build/maintain this kind of list over every potential places... (having as many as information in /homepage/ and put link could be better??)

**Comment by Yonet** [comment]
Good point @himorin. I've ended up on this page and saw the link was missing. I think it links from the homepage. If you want to move them, feel free. I'll merge this one for the complete list.

**Comment by himorin** [comment]
>  If you want to move them, feel free. I'll merge this one for the complete list.

yeah, let me file an issue to administrivia for tracking, and add relevant PRs, shortly...

**Review by cwilso — COMMENTED** [review]
LGTM.

**Pull request merged**
